In [1]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
  loss='sparse_categorical_crossentropy',
  metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 275s 24us/step


c:\Python\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - accuracy: 0.8593 - loss: 0.4770
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9569 - loss: 0.1497
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - accuracy: 0.9668 - loss: 0.1093
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9733 - loss: 0.0866
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9757 - loss: 0.0746
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9753 - loss: 0.0864


[0.07354967296123505, 0.9783999919891357]

In [7]:
import os

In [8]:
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

In [9]:
import tensorflow as tf

In [20]:
# Initialization of Tensors
x=tf.constant(4, shape=(1,1), dtype=tf.float32)
x=tf.constant([[1,2,3],[4,5,6]])

x=tf.ones((3,3))
x=tf.zeros((2,3))
x=tf.eye(3) # I for the identity matrix
x=tf.random.normal((3,3), mean=0, stddev=1)
x=tf.random.uniform((1,3), minval=0, maxval=1)
x=tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [21]:
x=tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [22]:
x=tf.eye(2)

In [23]:
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [24]:
x=tf.random.uniform((1,3), minval=0, maxval=1)

In [25]:
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.3475033 , 0.3654009 , 0.53264534]], dtype=float32)>

In [26]:
x=tf.range(9)

In [27]:
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [28]:
import tensorflow as tf

In [29]:
x=tf.constant(4, shape=(1,1), dtype=tf.float32)

In [30]:
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [31]:
x=tf.constant([[1,2,3],[4,5,6]])

In [32]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [33]:
x=tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [34]:
x=tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [35]:
x=tf.eye(3) # I for the identity matrix

In [36]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [37]:
x=tf.random.normal((3,3), mean=0, stddev=1)

In [38]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7698977 ,  0.44127432, -1.0591983 ],
       [ 0.0898312 , -1.1085615 ,  3.399993  ],
       [ 0.70948565, -0.13575733, -0.14459057]], dtype=float32)>

In [39]:
x=tf.random.uniform((1,3), minval=0, maxval=1)

In [40]:
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.17091942, 0.7977003 , 0.49042344]], dtype=float32)>

In [43]:
x=tf.range(start=1, limit=10, delta=2)

In [44]:
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [45]:
x=tf.cast(x, dtype=tf.float64)

In [46]:
x

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

In [47]:
#Mathematical operations
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])

z=tf.add(x,y)

In [48]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [49]:
z=tf.subtract(x,y)

In [50]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4])>

In [51]:
z=tf.divide(x,y)

In [52]:
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [53]:
z=tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [55]:
z=tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [57]:
z= x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [59]:
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y)
print(z)

tf.Tensor(
[[-0.5800888   0.07644355  0.41539526  0.3789925 ]
 [ 0.14634246  0.6009672  -0.57738626 -0.22087735]], shape=(2, 4), dtype=float32)


In [61]:
#indexing
x= tf.constant([0,1,1,2,3,1,2,3])
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [62]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [64]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [67]:
indices=tf.constant([0,3])
x_ind=tf.gather(x,indices)

x=tf.constant([[1,2],
               [3,4],
               [5,6]])
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [69]:
print(x[0:2,:])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [70]:
#reshaping
x=tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [71]:
x=tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [72]:
x=tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
